### ISSUE TITLE
`@import` tilde support

### ISSUE THREAD

**Issue by mbolli** [koluch/esbuild-plugin-sass#55]
Maybe it's just me, but I can't seem to make webpack-style  `@import '~bulma/sass/utilities/_all';` to work.

I don't know if that's in the scope of this plugin though.

```
      detail: sass.Exception [Error]: Can't find stylesheet to import.
        ╷
      5 │ @import "~bulma/sass/utilities/_all";
        │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        ╵
        assets/css/admin.scss 5:9  root stylesheet
          at Object.wrapException (/mnt/c/Users/micha/PhpstormProjects/moxiframework/node_modules/.pnpm/sass@1.47.0/node_modules/sass/sass.dart.js:1246:17)
          at _EvaluateVisitor1._evaluate0$_loadStylesheet$4$baseUrl$forImport (/mnt/c/Users/micha/PhpstormProjects/moxiframework/node_modules/.pnpm/sass@1.47.0/node_modules/sass/sass.dart.js:79287:19)
          at _EvaluateVisitor1._evaluate0$_loadStylesheet$3$forImport (/mnt/c/Users/micha/PhpstormProjects/moxiframework/node_modules/.pnpm/sass@1.47.0/node_modules/sass/sass.dart.js:79316:19)
          at _EvaluateVisitor__visitDynamicImport_closure1.call$0 (/mnt/c/Users/micha/PhpstormProjects/moxiframework/node_modules/.pnpm/sass@1.47.0/node_modules/sass/sass.dart.js:81027:21)
          at _EvaluateVisitor1._evaluate0$_withStackFrame$1$3 (/mnt/c/Users/micha/PhpstormProjects/moxiframework/node_modules/.pnpm/sass@1.47.0/node_modules/sass/sass.dart.js:80241:25)
          at _EvaluateVisitor1._evaluate0$_withStackFrame$3 (/mnt/c/Users/micha/PhpstormProjects/moxiframework/node_modules/.pnpm/sass@1.47.0/node_modules/sass/sass.dart.js:80247:19)
          at _EvaluateVisitor1._evaluate0$_visitDynamicImport$1 (/mnt/c/Users/micha/PhpstormProjects/moxiframework/node_modules/.pnpm/sass@1.47.0/node_modules/sass/sass.dart.js:79251:19)
          at _EvaluateVisitor1.visitImportRule$1 (/mnt/c/Users/micha/PhpstormProjects/moxiframework/node_modules/.pnpm/sass@1.47.0/node_modules/sass/sass.dart.js:79244:16)
          at ImportRule0.accept$1$1 (/mnt/c/Users/micha/PhpstormProjects/moxiframework/node_modules/.pnpm/sass@1.47.0/node_modules/sass/sass.dart.js:84197:22)
          at ImportRule0.accept$1 (/mnt/c/Users/micha/PhpstormProjects/moxiframework/node_modules/.pnpm/sass@1.47.0/node_modules/sass/sass.dart.js:84200:19),
      location: [Object],
      notes: [Array],
      pluginName: 'sass',
      text: "Can't find stylesheet to import.\n" +
        '\x1B[34m  ╷\x1B[0m\n' +
        '\x1B[34m5 │\x1B[0m @import \x1B[31m"~bulma/sass/utilities/_all"\x1B[0m;\n' +
        '\x1B[34m  │\x1B[0m \x1B[31m        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\x1B[0m\n' +
        '\x1B[34m  ╵\x1B[0m\n' +
        '  assets/css/admin.scss 5:9  root stylesheet'
```

**Comment by mbolli** [comment]
Any comment on this? I have to retain the whole webpack stack just to build my scss, it would be nice if esbuild could handle it as well...

**Comment by koluch** [comment]
Hi @mbolli,

Sorry for late response, I have been very busy recently.

Sorry, but no, this style of imports is not supported by this plugin. It would require to do a lot of guesses about project structure and would cause a lot of troubles in the future. So, this functionality is out of scope of this plugin
